services:
  db:
    image: postgres:16.1
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dog-club
    ports:
      - "5432:5432"